const characterImages: Record<string, string> = {
  "Luke Skywalker": "/images/characters/luke.jpeg",
  "C-3PO": "images/characters/c-3po.jpeg",
  "R2-D2": "/images/characters/r2-d2.jpeg",
  "Darth Vader": "/images/characters/vader.jpg",
  "Leia Organa": "/images/characters/leia.jpeg",
  "Owen Lars": "/images/characters/owen.jpeg",
  "Beru Whitesun lars": "/images/characters/beru.jpg",
  "R5-D4": "/images/characters/r5-d4.webp",
  "Biggs Darklighter": "/images/characters/biggs.jpeg",
  "Obi-Wan Kenobi": "/images/characters/kenobi.jpg",
  "Anakin Skywalker": "/images/characters/anakin.jpg",
  "Wilhuff Tarkin": "/images/characters/tarkin.png",
  Chewbacca: "/images/characters/chewbacca.jpeg",
  "Han Solo": "/images/characters/han.jpg",
  Greedo: "/images/characters/greedo.jpg",
  "Jabba Desilijic Tiure": "/images/characters/jabba.webp",
  "Wedge Antilles": "/images/characters/wedge.jpg",
  "Jek Tono Porkins": "/images/characters/jek.jpg",
  Yoda: "/images/characters/yoda.jpg",
  Palpatine: "/images/characters/palpatine.webp",
  "Boba Fett": "/images/characters/boba.jpeg",
  "IG-88": "/images/characters/ig-88.jpeg",
  Bossk: "/images/characters/bossk.jpg",
  "Lando Calrissian": "/images/characters/lando.jpg",
  Lobot: "/images/characters/lobot.avif",
  Ackbar: "/images/characters/ackbar.jpg",
  "Mon Mothma": "/images/characters/mothma.jpeg",
  "Arvel Crynyd": "/images/characters/arvel.jpg",
  "Wicket Systri Warrick": "/images/characters/wicket.jpeg",
  "Nien Nunb": "/images/characters/nien.jpeg",
  "Qui-Gon Jinn": "/images/characters/qui-gon.png",
  "Nute Gunray": "/images/characters/nute.jpeg",
  "Finis Valorum": "/images/characters/valorum.avif",
  "Padmé Amidala": "/images/characters/padme.png",
  "Jar Jar Binks": "/images/characters/jarjar.avif",
  "Roos Tarpals": "/images/characters/roos.webp",
  "Rugor Nass": "/images/characters/rugor.jpeg",
  "Ric Olié": "/images/characters/ric.jpeg",
  Watto: "/images/characters/watto.jpg",
  Sebulba: "/images/characters/sebulba.jpeg",
  "Quarsh Panaka": "/images/characters/panaka.jpeg",
  "Shmi Skywalker": "/images/characters/shmi.avif",
  "Darth Maul": "/images/characters/maul.jpeg",
  "Bib Fortuna": "/images/characters/bib.jpg",
  "Ayla Secura": "/images/characters/ayla.jpg",
  "Ratts Tyerel": "/images/characters/ratts.jpeg",
  "Dud Bolt": "/images/characters/dud.jpg",
  Gasgano: "/images/characters/gasgano.png",
  "Ben Quadinaros": "/images/characters/ben.jpeg",
  "Mace Windu": "/images/characters/windu.jpeg",
  "Ki-Adi-Mundi": "/images/characters/mundi.jpeg",
  "Kit Fisto": "/images/characters/kit.webp",
  "Eeth Koth": "/images/characters/eeth.jpeg",
  "Adi Gallia": "/images/characters/adi.jpeg",
  "Saesee Tiin": "/images/characters/saesee.jpeg",
  "Yarael Poof": "/images/characters/yarael.avif",
  "Plo Koon": "/images/characters/plo.jpeg",
  "Mas Amedda": "/images/characters/mas.webp",
  "Gregar Typho": "/images/characters/typho.jpeg",
  Cordé: "/images/characters/corde.jpeg",
  "Cliegg Lars": "/images/characters/cliegg.jpeg",
  "Poggle the Lesser": "/images/characters/poggle.jpeg",
  "Luminara Unduli": "/images/characters/luminara.jpeg",
  "Barriss Offee": "/images/characters/barriss.jpg",
  Dormé: "/images/characters/dorme.jpg",
  Dooku: "/images/characters/dooku.jpeg",
  "Bail Prestor Organa": "/images/characters/bail.webp",
  "Jango Fett": "/images/characters/jango.webp",
  "Zam Wesell": "/images/characters/zam.jpg",
  "Dexter Jettster": "/images/characters/dexter.jpeg",
  "Lama Su": "/images/characters/lama.webp",
  "Taun We": "/images/characters/taun.jpg",
  "Jocasta Nu": "/images/characters/jocasta.jpeg",
  "R4-P17": "/images/characters/r4-p17.jpeg",
  "Wat Tambor": "/images/characters/wat.jpeg",
  "San Hill": "/images/characters/san.jpeg",
  "Shaak Ti": "/images/characters/shaak.jpg",
  Grievous: "/images/characters/grievous.jpeg",
  Tarfful: "/images/characters/tarfful.jpeg",
  "Raymus Antilles": "/images/characters/raymus.webp",
  "Sly Moore": "/images/characters/sly.jpeg",
  "Tion Medon": "/images/characters/tion.jpeg",
};

export default characterImages;
